⚠️ This project is mandatory for certification bloc #2.

# DATA PROJET TINDER

![Tinder](https://full-stack-assets.s3.eu-west-3.amazonaws.com/M03-EDA/Tinder-Symbole.png)

## Speed Dating with Tinder

### Company's description 📇

<a href="https://tinder.com/" target="_blank">Tinder</a> is an online dating and geosocial networking application. In Tinder, users "swipe right" to like or "swipe left" to dislike other users' profiles, which include their photos, a short bio, and a list of their interests.

Tinder was launched by Sean Rad at a hackathon held at the Hatch Labs incubator in West Hollywood in 2012.

As of 2021, Tinder has recorded more than 65 billion matches worldwide.

## Project 🚧

The marketing team needs help on a new project. They are experiencing a decrease in the number of matches, and they are trying to find a way to understand **what makes people interested into each other**. 

They decided to run a speed dating experiment with people who had to give Tinder lots of informations about themselves that could ultimately reflect on ther dating profile on the app.

Tinder then gathered the data from this experiment. Each row in the dataset represents one speed date between two people, and indicates wether each of them secretly agreed to go on a second date with the other person.

## Goals 🎯

Use the dataset to understand what makes people interested into each other to go on a second date together:
* You may use descriptive statistics
* You may use visualisations

## Scope of this project 🖼️

Data was gathered from participants in experimental speed dating events from 2002-2004. During the events, the attendees would have a four minute "first date" with every other participant of the opposite sex. At the end of their four minutes, participants were asked if they would like to see their date again. They were also asked to rate their date on six attributes: Attractiveness, Sincerity, Intelligence, Fun, Ambition, and Shared Interests.

The dataset also includes questionnaire data gathered from participants at different points in the process. These fields include: demographics, dating habits, self-perception across key attributes, beliefs on what others find valuable in a mate, and lifestyle information. See the Speed Dating Data Key document below for details.

[Dataset](https://full-stack-assets.s3.eu-west-3.amazonaws.com/M03-EDA/Speed+Dating+Data.csv)

[Dataset Description](https://full-stack-assets.s3.eu-west-3.amazonaws.com/M03-EDA/Speed+Dating+Data+Key.doc)

## Helpers 🦮

To help you achieve this project, here are a few tips that should help you

Data Exploration Ideas :
* What are the least desirable attributes in a male partner? Does this differ for female partners?
* How important do people think attractiveness is in potential mate selection vs. its real impact?
* Are shared interests more important than a shared racial background?
* Can people accurately predict their own perceived value in the dating market?
* In terms of getting a second date, is it better to be someone's first speed date of the night or their last?

## Deliverable 📬

To complete this project, your team should deliver:

A notebook with:
* descriptive statistics
* visualisations
* captions and interpretations on how the stats and visualisations are relevant to why people agree to a second date

# Librairie et chargement datas

In [46]:
import plotly.express as px
import pandas as pd

In [47]:
# import chardet

# # Lire le fichier en mode binaire pour détecter l'encodage
# with open('Speed+Dating+Data.csv', 'rb') as f:
#     raw_data = f.read()
    
# # Détecter l'encodage
# result = chardet.detect(raw_data)
# print("Encodage détecté:", result['encoding'])
# print("Confiance:", result['confidence'])
# print("Langue:", result['language'])

In [48]:
df = pd.read_csv('Speed+Dating+Data.csv', encoding='Windows-1252')
df.to_csv('Speed_Dating_Window-1252.csv', index=False)

# EDA

## Analyse composantes generals du dataframe
    1- 8378 ligne et 195 colonnes
    2-  Nombre de sessions :21, 551 participants, pour un total de 4189.0 rendez-vous.
        Nombre moyen de participants par session : 26.24
        Nombre total de 'matchs' : 690.0, soit en moyenne par session: 32.86 match sur 200 rdv, (16,5% des rdv)

In [36]:
print(df.shape)
df.head()

(8378, 195)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [6]:
df_isna = df.isna().sum()
df_isna[df_isna >0]

id             1
positin1    1846
pid           10
int_corr     158
age_o        104
            ...
attr5_3     6362
sinc5_3     6362
intel5_3    6362
fun5_3      6362
amb5_3      6362
Length: 182, dtype: int64

In [7]:
print(df.info())
display(df.describe(include='all'))
#print(df.describe(include='all'))
print(f"nombre de cellules manquantes : {df.isnull().sum().sum()}")
print(f"le nombre de lignes avec des cellules manquantes : {df.isnull().any(axis=1).sum()}")
print(df['gender'].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Columns: 195 entries, iid to amb5_3
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB
None

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,...,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,...,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,...,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,...,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,...,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,...,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,...,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,...,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

nombre de cellules manquantes : 432016
le nombre de lignes avec des cellules manquantes : 8378
gender
1    4194
0    4184
Name: count, dtype: int64

In [53]:
nb_participants  = len(df['iid'].unique())
nb_sessions = len(df['wave'].unique())
nb_rdv = (len(df))/2  # chaque rendez-vous est enregistré deux fois (une fois par participant)
print(f"Nombre de sessions :{nb_sessions}, {nb_participants} participants, pour un total de {nb_rdv} rendez-vous.")
moy_participants_per_session = round(nb_participants / nb_sessions, 2)
print(f"Nombre moyen de participants par session : {moy_participants_per_session}")
nb_matches = (df['match'].sum())/2
moy_matches_per_session = round(nb_matches / nb_sessions, 2)
print(f"Nombre total de 'matchs' : {nb_matches}, soit en moyenne par session: {moy_matches_per_session} ")
moy_rdv_per_session = round(nb_rdv / nb_sessions, 2)
print(f"Nombre moyen de rdv par session : {moy_rdv_per_session}, soit taux de conversion de  {round(moy_matches_per_session*100/moy_rdv_per_session, 2)}% par session.")

Nombre de sessions :21, 551 participants, pour un total de 4189.0 rendez-vous.
Nombre moyen de participants par session : 26.24
Nombre total de 'matchs' : 690.0, soit en moyenne par session: 32.86
Nombre moyen de rdv par session : 199.48, soit taux de conversion de  16.47% par session.

## Analyses comparatives
    1- Repartission H/F: 277 hommes et 274 femmmes, répartission homogène
    2- Aucun participant n'a de facon déclaré, participé a plusieurs session

### Repartision par Age et genre de la population d'étude

In [55]:
df_unique = df.drop_duplicates(subset=['iid'])
df_unique['gender_label'] = df_unique['gender'].map({0: 'Femme', 1: 'Homme'})
fig = px.histogram(df_unique, x='age', color='gender_label', barmode='group',
                   title='Age Distribution by Gender',
                   color_discrete_map={'Femme': '#EF553B',  # Rouge pour 0 (homme)
                                      'Homme': '#636EFA'},  # Bleu pour 1 (femme))
                    text_auto=True)  # Affiche les valeurs sur les barres
fig.show()

C:\Users\Micka\AppData\Local\Temp\ipykernel_24628\3163036521.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
# Créer un tableau de contingence
tableau = pd.crosstab(df_unique['age'], df_unique['gender_label'])
print(tableau)

# Pour voir une ligne spécifique (ex: 27 ans)
print(f"\nÀ 27 ans:")
print(tableau.loc[27])

gender_label  Femme  Homme
age
18.0              0      1
19.0              1      1
20.0              3      2
21.0             14      8
22.0             24     20
23.0             32     24
24.0             29     27
25.0             29     26
26.0             31     24
27.0             28     40
28.0             19     28
29.0             17     23
30.0             14     22
31.0              3      4
32.0              3     10
33.0              7      5
34.0              7      4
35.0              4      0
36.0              2      2
37.0              0      1
38.0              1      0
39.0              0      1
42.0              0      1
55.0              1      0

À 27 ans:
gender_label
Femme    28
Homme    40
Name: 27.0, dtype: int64

### Comptage Homme / Femme par wave

In [34]:
df_compt_HF = df_unique.groupby('wave')['gender'].value_counts().unstack()    
df_compt_HF

gender   0   1
wave
1       10  10
2       19  16
3       10  10
4       18  18
5        9  10
6        5   5
7       16  16
8       10  10
9       20  20
10       9   9
11      21  21
12      14  14
13      10   9
14      20  18
15      18  19
16       6   8
17      10  14
18       6   6
19      15  15
20       6   7
21      22  22

In [45]:
fig = px.pie(df_unique, names='gender_label',
                   title='Age Distribution by Gender',
                   color_discrete_map={'Femme': '#636EFA',  # Rouge pour 0 (homme)
                                      'Homme': '#EF553B'})  # Bleu pour 1 (femme))
fig.update_traces(texttemplate='%{label}<br>%{value} (%{percent})')
fig.show()

### Verification participation unique (Verification qu'un participant n'a pas participé a plusieur session)

In [49]:
# Compter combien de waves différentes pour chaque iid
waves_par_iid = df.groupby('iid')['wave'].nunique()
# Filtrer ceux qui sont dans plus d'une wave
iid_multiples = waves_par_iid[waves_par_iid > 1]
print(f" Nombre de participants dans plusieurs waves: {iid_multiples.count()}")

 Nombre de participants dans plusieurs waves: 0

### importance de la race, de la religion, du satus social dans le choix

In [ ]:
df_egal_HF = df.groupby(['Gender', 'Age', 'Education'])['MonthlyIncome'].mean().reset_index()
fig = px.bar(df_egal_HF, x='Age', y='MonthlyIncome', color='Gender', barmode='group', facet_col='Education', template="plotly_dark")
fig.show()

## PREPARATION DU ML D'ANALYSE

In [ ]:
# Reset index pour avoir les colonnes disponibles après groupby
df_egal_HF = df.groupby(['gender', 'Age', 'Education'])['MonthlyIncome'].mean().reset_index()
fig = px.bar(df_egal_HF, x='Age', y='MonthlyIncome', color='gender', barmode='group', facet_col='Education', template="plotly_dark")
fig.show()